apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: secretsyncs.beansnet.net
spec:
  group: beansnet.net
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                sourceSecret:
                  type: string
                destinationNamespaces:
                  type: array
                  items:
                    type: string
  scope: Namespaced
  names:
    plural: secretsyncs
    singular: secretsync
    kind: SecretSync
    shortNames:
    - ss
