apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-syncopier
rules:
- apiGroups: ["beansnet.net"]
  resources: ["secretsyncs"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-secrets-global
subjects:
- kind: ServiceAccount
  name: secret-syncopier
  namespace: secret-syncopier
roleRef:
  kind: ClusterRole
  name: secret-syncopier
  apiGroup: rbac.authorization.k8s.io
