apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-syncopier
  namespace: secret-syncopier
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-syncopier
  namespace: secret-syncopier
  labels:
    app: secret-syncopier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-syncopier
  template:
    metadata:
      labels:
        app: secret-syncopier
    spec:
      serviceAccountName: secret-syncopier
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: secret-syncopier
        image: bentastic27/k8s-secret-syncopier:latest